

# This file was *autogenerated* from the file cryptanalyse.sage
from sage.all_cmdline import *   # import sage library

_sage_const_10 = Integer(10); _sage_const_20 = Integer(20); _sage_const_50 = Integer(50); _sage_const_100 = Integer(100); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
load("gghIntoFile.sage")

def LLLattack(pubkey, e):
    LLL_pubkey=pubkey.LLL()
    v = BabaiNearestPlaneAlgorithm(LLL_pubkey, e)
    m = pubkey.solve_left(v)
    return m


def test_LLL_attack():
    """Test attaque LLL sur un chiffrement GGH"""
    n = [_sage_const_10 , _sage_const_20 , _sage_const_50 , _sage_const_100 ]
    for size in n:
        ggh = GGH(size)
        pubkey = ggh.pubkey

        # Créer un message aléatoire
        m = vector(ZZ, [randint(-size, size) for _ in range(size)])
        e = ggh.encrypt(m, delta=_sage_const_3 )

        m_decrypted = LLLattack(pubkey, e)

        assert m == m_decrypted, f"Déchiffrement échoué avec un LLL pour un code de taille {size}"
        print(f"Chiffrement/Déchiffrement réussi après un LLL pour un code de taille {size}")

def embeding_attack(pubkey, e):
    n = pubkey.nrows()
    e_embed = vector(ZZ, list(e) + [_sage_const_1 ])
    B_embed = pubkey.augment(vector(ZZ, [_sage_const_0 ]*n))
    B_embed = B_embed.stack(e_embed)
    return B_embed[_sage_const_0 , :n]

def test_embeding_attack():
    """Test attaque par embeeding sur un chiffrement GGH"""
    n = [_sage_const_10 , _sage_const_20 , _sage_const_50 , _sage_const_100 ]
    for size in n:
        ggh = GGH(size)
        pubkey = ggh.pubkey

        # Créer un message aléatoire
        m = vector(ZZ, [randint(-size, size) for _ in range(size)])
        print(m)
        e = ggh.encrypt(m, delta=_sage_const_3 )

        m_decrypted = embeding_attack(pubkey, e)
        print(m_decrypted)

        assert m == m_decrypted, f"Déchiffrement échoué avec une attaque par embeeding pour un code de taille {size}"
        print(f"Chiffrement/Déchiffrement réussi après une attaque par embeeding pour un code de taille {size}")

test_embeding_attack()

test_LLL_attack()

